version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: performance-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce-network

  grafana:
    image: grafana/grafana:latest
    container_name: performance-grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - ecommerce-network
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: performance-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - ecommerce-network

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: performance-mongodb-exporter
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://ecommerce-mongodb:27017
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
    name: e-commerce-microservices_ecommerce-network
